name: ShoPHP
on:
    push:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                php-version: '8.3'

            - name: Install Composer Dependencies
              working-directory: ./app
              run: composer install --prefer-dist

            - name: Run Tests
              working-directory: ./app
              run: composer run-phpunit

            - name: Build and push Docker images
              run: |
                docker build --target app -t nicorafales/php-composer:1.1.0 -f ./Docker/php/Dockerfile .
                docker build -t nicorafales/nginx-php:1.0.0 -f ./Docker/nginx/Dockerfile .
                docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PWD }}
                docker push nicorafales/php-composer:1.1
                docker push nicorafales/nginx-php:1.0